---
title: "Harmonize neonatal-related attributes in cMD metadata"
author:
  - Britney Pheng
  - Sehyun Oh
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
    html:
        fontsize: 14pxs
        toc: true
        top-depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE,
                      collapse = TRUE)
```

```{r}
suppressPackageStartupMessages({
    library(curatedMetagenomicData)
})
```

```{r}
class(sampleMetadata)
dim(sampleMetadata)
head(colnames(sampleMetadata), 10)
sampleMetadata[1:4, 1:10]
```

```{r}
curated <- readr::read_csv("~/OmicsMLRepo/OmicsMLRepoData/inst/extdata/cMD_curated_sampleMetadata.csv")
```

```{r}
neonatal_cols <- c("born_method", 
                   "gestational_age",
                   "premature",
                   "birth_weight",
                   "lactating",
                   "c_section_type",
                   "feeding_practice",
                   "formula_first_day",
                   "breastfeeding_duration")
```

```{r}
## Some samples were used in more than one studies
sum(duplicated(sampleMetadata$sample_id))
```

```{r}
tb <- sampleMetadata %>%
    mutate(curation_id = paste(study_name, sample_id, sep = ":")) %>%
    select(curation_id = curation_id,
           neonatal_cols)

head(tb)
```

Are these neonatal phenotype or mother's phenotye?
```{r}
table(sampleMetadata$age_category[which(!is.na(sampleMetadata$feeding_practice))])
table(sampleMetadata$age_category[which(!is.na(sampleMetadata$lactating))])
```

